[Mesh]
file = "meshes/cube_4.h5"

[Numerics]
order = 3
basis = "LagrangeHex"

[Stepper]
start = 0.0
end = 1.0 
timestep = 1e-3
type = "RK4"

[Physics]
name = "Euler"
dim = 3
gamma = 1.4
GasConstant = 1.0
convective_flux_fcn = "HLLC"

[InitialCondition]
name = "IsentropicVortex"
data = [1.0, 1.0, 1.0, 1.0, 5.0]

#name = "Uniform"
#data = [1.0, 0.1, 0.1, 0.1, 2.5]
