# skip_solve = true
# disable_all_outputs = true
checkpoint_interval = 100
# restart_interval = 1

[Mesh]
file = "quad_2x2.h5"

[Numerics]
order = 2
basis = "LagrangeQuad"

[Stepper]
start = 0.0
end = 1.0
timestep = 1e-3
type = "SSPRK3"

[Physics]
name = "IdealGas"
dim = 2
gamma = 1.4

[Equation]
name = "Euler"
inviscid_flux = "HLLC"
init_type = "IsentropicVortex"

[Output]
prefix = "solutions/vortex"
variables = ["Rho", "VelX", "VelY", "P", "T", "Mach"]
interval = 100
