[Mesh]
file = "meshes/box_256x256.h5"

[Numerics]
order = 2
basis = "LagrangeQuad"
#basis = "LegendreQuad"

[Stepper]
start = 0.0
end = 1.0 
timestep = 0.001
type = "RK4"

[Physics]
name = "Euler"
dim = 2
gamma = 1.4
GasConstant = 1.0
convective_flux_fcn = "HLLC"

[InitialCondition]
name = "IsentropicVortex"
data = [1.0, 1.0, 1.0, 1.0, 5.0]

